FROM debian:latest


RUN apt-get update \
    && apt-get install -y  apache2 \
    && apt-get -y autoclean


WORKDIR /app

COPY build /app/build
RUN mv /app/build/* /var/www/html/

RUN a2enmod rewrite

RUN rm /etc/apache2/ports.conf
RUN rm /etc/apache2/apache2.conf
RUN rm /etc/apache2/sites-enabled/000-default.conf

COPY ports.conf /etc/apache2/ports.conf
COPY apache2.conf /etc/apache2/apache2.conf
COPY 000-default.conf /etc/apache2/sites-enabled/000-default.conf

COPY .htaccess /var/www/html/.htaccess

ENTRYPOINT service apache2 restart && bash
