version: "3"


volumes:
  mongo_data:
    external: true

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
    networks:
      - shvl-net
  nginx-balancer:
    image: nginx:latest
    hostname: nginx-balancer
    container_name: nginx-balancer
    volumes:
      - ./nginx-backend-balancer:/etc/nginx/templates
    depends_on:
      - backend
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=
      - NGINX_PORT=5000
      - INSTANCE_URL=http://backend
      - INSTANCE_PORT=5001
    networks:
      - shvl-net
  mongo:
    hostname: mongo
    container_name: mongo
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shvl-net
  mail:
    image: "mailhog/mailhog"
    hostname: mail
    container_name: mail
    environment:
      - VIRTUAL_HOST=mail
      - MH_OUTGOING_SMTP=/home/smtp/configs.json
      - MH_SMTP_BIND_ADDR=mail:1025
    working_dir: /home/smtp
    volumes:
      - ./backend/smtp.json:/home/smtp/configs.json
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - shvl-net
  backend:
    hostname: development
    links:
      - mongo
    image: "igabriele/docker-compose-puppeteer"
    working_dir: /home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEFAULT_EMAIL_HOST_BACKEND=mail
      - DEFAULT_EMAIL_HOST_PORT_BACKEND=1025
      - VIRTUAL_HOST=mail
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb://mongo/backend-dev
      - SENDGRID_KEY=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
      - MASTER_KEY=Sc4pGDcr8NeKPNouEXOQp1v784Dutmlt
      - JWT_SECRET=8EZ0QdhBOntJSuyZHXJHfVB4NCJQ4KqM
      - DEFAULT_EMAIL_BACKEND=adanyanezgonzalez@gmail.com
      - API_ROOT=/
      - WEB3_PROVIDERS_HTTP_PROVIDER=https://mainnet.infura.io/v3/836e6a8258c14cae987e4dbc2dc4fe3b
      - WEB3_PROJECT_ID=836e6a8258c14cae987e4dbc2dc4fe3b
      - WEB3_PROJECT_SECRET=8b9d757732c64cbba50f5def3e3529bf
      - OPENSEA_API_KEY=2f6f419a083c46de9d83ce3dbe7db601
    volumes:
      - ./backend:/home/node/app
    ports:
      - "5001"
    command: "npm run dev"
    networks:
      - shvl-net
  frontend:
    restart: always
    hostname: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
      - NODE_ENV=development
      - REACT_APP_BASE_LAYOUT_CONFIG_KEY='metronic-react-demo1-8037'
      - REACT_APP_API_URL=https://preview.keenthemes.com/metronic8/laravel/api
      - REACT_APP_VERSION=v8.0.38
      - REACT_APP_THEME_NAME=Metornic
      - REACT_APP_THEME_DEMO=demo1
      - REACT_APP_BOOTSTRAP_DOCS_LINK=https://getbootstrap.com/docs/5.0
      - REACT_APP_SASS_PATH=src/_metronic/assets/sass/core/components
      - REACT_APP_SASS_VARIABLES_PATH=src/_metronic/assets/sass/core/components/_variables.scss
      - REACT_APP_PURCHASE_URL=https://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469
      - REACT_APP_PREVIEW_URL=https://preview.keenthemes.com/metronic8/react/demo1/
      - REACT_APP_PREVIEW_REACT_URL=https://preview.keenthemes.com/metronic8/react
      - REACT_APP_PREVIEW_DOCS_URL=https://preview.keenthemes.com/metronic8/react/docs
      - REACT_APP_THEME_API_URL=https://preview.keenthemes.com/theme-api/api
      - REACT_APP_BACKEND_URL=http://backend:5000/
      - REACT_APP_MASTER_KEY=Sc4pGDcr8NeKPNouEXOQp1v784Dutmlt
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: "yarn start"
    networks:
      - shvl-net
    depends_on:
      - backend
      - nginx-balancer
      - mongo
      - mail
      - nginx-proxy
  cron-jobs:
    hostname: cron-jobs
    container_name: cron-jobs
    build:
      context: ./cron_jobs
      dockerfile: ./Dockerfile
    networks:
      - shvl-net
    depends_on:
      - backend
      - nginx-balancer
      - nginx-proxy
networks:
  shvl-net:
    external: true


