version: "2"


volumes:
  mongo_data:
    external: true
  portainer_data:
    external: true
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: reverse_proxy-caym-server.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
  portainer:
    image: portainer/portainer
    hostname: "portainer-caym-server.com"
    container_name: portainer-caym-server.com
    restart: always
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer-ce
    environment:
      - VIRTUAL_HOST=portainer-caym-server.com
  mongo:
    container_name: mongo-caym-server.com
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  production:
    restart: always
    hostname: "production-caym-server.com"
    container_name: production-caym-server.com
    links:
      - mongo
    image: "node:14"
    working_dir: /home/node/app
    environment:
      - DEFAULT_EMAIL_HOST_BACKEND=mail-caym-server.com
      - DEFAULT_EMAIL_HOST_PORT_BACKEND=1025
      - NODE_ENV=production
      - VIRTUAL_HOST=production-caym-server.com
      - PORT=3000
      - MONGO_URI=mongodb://mongo/backend-prod
    volumes:
      - ./backend:/home/node/app
    ports:
      - "3000:3000"
    command: "npm run prod"
  test:
    hostname: "test-caym-server.com"
    container_name: test-caym-server.com
    links:
      - mongo
    image: "node:14"
    working_dir: /home/node/app
    environment:
      - DEFAULT_EMAIL_HOST_BACKEND=mail-caym-server.com
      - DEFAULT_EMAIL_HOST_PORT_BACKEND=1025
      - VIRTUAL_HOST=test-caym-server.com
      - NODE_ENV=test
      - PORT=4000
      - MONGO_URI=mongodb://mongo/backend-test
    volumes:
      - ./backend:/home/node/app
    ports:
      - "4000:4000"
    command: "npm run test"
  mail:
    image: "mailhog/mailhog"
    hostname: "mail-caym-server.com"
    container_name: mail-caym-server.com
    environment:
      - VIRTUAL_HOST=mail-caym-server.com
      - MH_OUTGOING_SMTP=/home/smtp/configs.json
      - MH_SMTP_BIND_ADDR=mail-caym-server.com:1025
    working_dir: /home/smtp
    volumes:
      - ./backend/smtp.json:/home/smtp/configs.json
    ports:
      - "1025:1025"
      - "8025:8025"
  development:
    hostname: "development-caym-server.com"
    container_name: development-caym-server.com
    links:
      - mongo
    image: "igabriele/docker-compose-puppeteer"
    working_dir: /home/node/app
    environment:
      - DEFAULT_EMAIL_HOST_BACKEND=mail-caym-server.com
      - DEFAULT_EMAIL_HOST_PORT_BACKEND=1025
      - VIRTUAL_HOST=development-caym-server.com
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo/backend-dev
    volumes:
      - ./backend:/home/node/app
    ports:
      - "5000:5000"
    command: "npm run dev"
  owncloud:
    hostname: "owncloud-caym-server.com"
    container_name: owncloud-caym-server.com
    image: owncloud/server:10.7
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db-owncloud
      - redis-owncloud
    environment:
      - OWNCLOUD_DOMAIN=localhost:8080
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db-owncloud-caym-server.com
      - OWNCLOUD_DB_PORT=3306
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis-owncloud-caym-server.com
      - OWNCLOUD_REDIS_PORT=6379
      - VIRTUAL_HOST=owncloud-caym-server.com
      - PORT=8080
    healthcheck:
      test: [ "CMD", "/usr/bin/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data
  db-owncloud:
    hostname: "db-owncloud-caym-server.com"
    container_name: db-owncloud-caym-server.com
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - VIRTUAL_HOST=db-owncloud-caym-server.com
    healthcheck:
      test: [ "CMD", "/usr/bin/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
    - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup
  redis-owncloud:
    hostname: "redis-owncloud-caym-server.com"
    container_name: redis-owncloud-caym-server.com
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
      - VIRTUAL_HOST=redis-owncloud-caym-server.com

    healthcheck:
      test: [ "CMD", "/usr/bin/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis
    ports:
      - "6379:6379"