version: "3"


volumes:
  mongo_data:
    external: true

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: reverse_proxy-caym-server.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
    networks:
      - shvl-net
  nginx-balancer:
    image: nginx:latest
    hostname: "balancer-caym-server.com"
    container_name: balancer-caym-server.com
    volumes:
      - ./templates:/etc/nginx/templates
    depends_on:
      - backend
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=
      - NGINX_PORT=5000
      - INSTANCE_URL=http://development-caym-server.com
      - INSTANCE_PORT=5001
    networks:
      - shvl-net
  mongo:
    container_name: mongo-caym-server.com
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shvl-net
  mail:
    image: "mailhog/mailhog"
    hostname: "mail-caym-server.com"
    container_name: mail-caym-server.com
    environment:
      - VIRTUAL_HOST=mail-caym-server.com
      - MH_OUTGOING_SMTP=/home/smtp/configs.json
      - MH_SMTP_BIND_ADDR=mail-caym-server.com:1025
    working_dir: /home/smtp
    volumes:
      - ./backend/smtp.json:/home/smtp/configs.json
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - shvl-net
  backend:
    env_file:
      - ./backend/.env.development
    hostname: "development-caym-server.com"
    links:
      - mongo
    image: "igabriele/docker-compose-puppeteer"
    working_dir: /home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEFAULT_EMAIL_HOST_BACKEND=mail-caym-server.com
      - DEFAULT_EMAIL_HOST_PORT_BACKEND=1025
      - VIRTUAL_HOST=development-caym-server.com
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb://mongo/backend-dev
    volumes:
      - ./backend:/home/node/app
    ports:
      - "5001"
    command: "npm run dev"
    networks:
      - shvl-net
  frontend:
    restart: always
    hostname: "app-development-caym-server.com"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
    container_name: webapp-dev
    working_dir: /app
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: "yarn start"
    networks:
      - shvl-net
    depends_on:
      - backend
      - nginx-balancer
      - mongo
      - mail
      - nginx-proxy
  cron-jobs:
    hostname: "cron-jobs-caym-server.com"
    build:
      context: ./cron_jobs
      dockerfile: ./Dockerfile
    container_name: cron-jobs
    networks:
      - shvl-net
    depends_on:
      - backend
      - nginx-balancer
      - nginx-proxy
networks:
  shvl-net:
    external: true