version: "3"
volumes:
  mongo_data:
    external: true
  portainer_data:
    external: true

services:
  backend:
    hostname: backend
    links:
      - mongo
    working_dir: /home/node/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://shvldb:shvldb2022@mongo:27017/backend-prod
      - DEFAULT_EMAIL_HOST_BACKEND=http://mail
      - CHOKIDAR_USEPOLLING=true
      - DEFAULT_EMAIL_HOST_PORT_BACKEND=1025
      - NODE_ENV=development
      - SENDGRID_KEY=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
      - MASTER_KEY=Sc4pGDcr8NeKPNouEXOQp1v784Dutmlt
      - JWT_SECRET=8EZ0QdhBOntJSuyZHXJHfVB4NCJQ4KqM
      - DEFAULT_EMAIL_BACKEND=adanyanezgonzalez@gmail.com
      - API_ROOT=/
      - WEB3_PROVIDERS_HTTP_PROVIDER=https://rinkeby.infura.io/v3/3474ad1afab24ab49d8874963e26eeb7
    volumes:
      - ./backend:/home/node/app
    ports:
      - "5001:5001"
    command: "npm run dev"
    networks:
      - shvl-net
  mongo:
    hostname: mongo
    container_name: mongo
    image: 'mongo'
    ports:
      - "27017:27017"
    environment:
      - VIRTUAL_HOST=mongo
      - MONGO_INITDB_ROOT_USERNAME=shvl
      - MONGO_INITDB_ROOT_PASSWORD=shvl2022
    volumes:
      - mongo_data:/data/db
    networks:
      - shvl-net
  cron-jobs:
    restart: always
    hostname: cron-jobs
    container_name: cron-jobs
    working_dir: /app
    volumes:
      - ./cron_jobs:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SELF_HOST=http://cron-jobs-server
      - SELF_PORT=4000
      - BACKEND_HOST=http://backend
      - BACKEND_PORT=5001
      - MASTER_KEY=Sc4pGDcr8NeKPNouEXOQp1v784Dutmlt
      - WEB3_PROJECT_ID=836e6a8258c14cae987e4dbc2dc4fe3b
      - WEB3_PROJECT_SECRET=8b9d757732c64cbba50f5def3e3529bf
      - OPENSEA_API_KEY=2f6f419a083c46de9d83ce3dbe7db601
    build:
      context: ./cron_jobs
      dockerfile: ./Dockerfile
    networks:
      - shvl-net
    depends_on:
      - backend
      - cron-jobs-server
  cron-jobs-server:
    restart: always
    hostname: cron-jobs-server
    container_name: cron-jobs-server
    working_dir: /app
    volumes:
      - ./cron_jobs-server:/app
    build:
      context: ./cron_jobs-server
      dockerfile: ./Dockerfile
    networks:
      - shvl-net
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: "nodemon index.js"
networks:
  shvl-net:
    external: true


