version: "3"


volumes:
  mongo_data:
    external: true

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy.shvl.ia
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
    environment:
      - DEFAULT_HOST=frontend.shvl.ia:3000
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
    networks:
      - shvl-net
  nginx-balancer:
    image: nginx:latest
    hostname: nginx-balancer.shvl.ia
    container_name: nginx-balancer.shvl.ia
    volumes:
      - ./nginx-backend-balancer:/etc/nginx/templates
    depends_on:
      - backend
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=
      - NGINX_PORT=5000
      - INSTANCE_URL=http://backend.shvl.ia
      - INSTANCE_PORT=5001
    networks:
      - shvl-net
  mongo:
    hostname: mongo.shvl.ia
    container_name: mongo.shvl.ia
    image: 'mongo'
    ports:
      - "27017:27017"

    environment:
      - VIRTUAL_HOST=mongo.shvl.ia
    volumes:
      - mongo_data:/data/db
    networks:
      - shvl-net
  mail:
    image: "mailhog/mailhog"
    hostname: mail.shvl.ia
    container_name: mail.shvl.ia
    environment:
      - VIRTUAL_HOST=mail.shvl.ia
      - MH_OUTGOING_SMTP=/home/smtp/configs.json
      - MH_SMTP_BIND_ADDR=mail:1025
    working_dir: /home/smtp
    volumes:
      - ./backend/smtp.json:/home/smtp/configs.json
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - shvl-net
  backend:
    hostname: development.shvl.ia
    links:
      - mongo
    image: "igabriele/docker-compose-puppeteer"
    working_dir: /home/node/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEFAULT_EMAIL_HOST_BACKEND=http://mail.shvl.ia
      - DEFAULT_EMAIL_HOST_PORT_BACKEND=1025
      - VIRTUAL_HOST=backend.shvl.ia
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb://mongo.shvl.ia/backend-dev
      - SENDGRID_KEY=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
      - MASTER_KEY=Sc4pGDcr8NeKPNouEXOQp1v784Dutmlt
      - JWT_SECRET=8EZ0QdhBOntJSuyZHXJHfVB4NCJQ4KqM
      - DEFAULT_EMAIL_BACKEND=adanyanezgonzalez@gmail.com
      - API_ROOT=/
      - WEB3_PROVIDERS_HTTP_PROVIDER=https://mainnet.infura.io/v3/836e6a8258c14cae987e4dbc2dc4fe3b
      - WEB3_PROJECT_ID=836e6a8258c14cae987e4dbc2dc4fe3b
      - WEB3_PROJECT_SECRET=8b9d757732c64cbba50f5def3e3529bf
      - OPENSEA_API_KEY=2f6f419a083c46de9d83ce3dbe7db601
    volumes:
      - ./backend:/home/node/app
    ports:
      - "5001"
    command: "npm run start"
    networks:
      - shvl-net
  frontend:
    restart: always
    hostname: frontend.shvl.ia
    container_name: frontend.shvl.ia
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=backend.shvl.ia
    networks:
      - shvl-net
    depends_on:
      - backend
      - nginx-balancer
      - mongo
      - mail
      - nginx-proxy
  cron-jobs:
    hostname: cron-jobs.shvl.ia
    container_name: cron-jobs.shvl.ia
    build:
      context: ./cron_jobs
      dockerfile: ./Dockerfile
    networks:
      - shvl-net
    depends_on:
      - backend
      - nginx-balancer
      - nginx-proxy
networks:
  shvl-net:
    external: true


