version: "3"


volumes:
  mongo_data:
    external: true
  portainer_data:
    external: true

services:
  backend:
    restart: always
    hostname: backend.shvl.ia
    links:
      - mongo
    image: "node:latest"
    working_dir: /home/node/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo.shvl.ia/backend-prod
      - DEFAULT_EMAIL_HOST_BACKEND=http://mail.shvl.ia
      - CHOKIDAR_USEPOLLING=true
      - DEFAULT_EMAIL_HOST_PORT_BACKEND=1025
      - NODE_ENV=production
      - SENDGRID_KEY=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
      - MASTER_KEY=Sc4pGDcr8NeKPNouEXOQp1v784Dutmlt
      - JWT_SECRET=8EZ0QdhBOntJSuyZHXJHfVB4NCJQ4KqM
      - DEFAULT_EMAIL_BACKEND=adanyanezgonzalez@gmail.com
      - API_ROOT=/
      - WEB3_PROVIDERS_HTTP_PROVIDER=https://mainnet.infura.io/v3/836e6a8258c14cae987e4dbc2dc4fe3b
      - WEB3_PROJECT_ID=836e6a8258c14cae987e4dbc2dc4fe3b
      - WEB3_PROJECT_SECRET=8b9d757732c64cbba50f5def3e3529bf
      - OPENSEA_API_KEY=2f6f419a083c46de9d83ce3dbe7db601
    volumes:
      - ./backend:/home/node/app
    ports:
      - "5001"
    command: "npm run start"
    networks:
      - shvl-net
  frontend:
    restart: always
    hostname: frontend.shvl.ia
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - shvl-net
    depends_on:
      - backend
  portainer:
    image: portainer/portainer
    hostname: portainer.shvl.ia
    container_name: portainer.shvl.ia
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer-ce
    environment:
      - VIRTUAL_HOST=portainer-caym-server.com
  nginx-balancer:
    image: nginx:latest
    hostname: nginx-balancer.shvl.ia
    container_name: nginx-balancer.shvl.ia
    volumes:
      - ./nginx-backend-balancer:/etc/nginx/templates
    depends_on:
      - backend
    ports:
      - "5000:5000"
      - "80:80"
    environment:
      - FRONTEND_NGINX_PORT=80
      - BACKEND_NGINX_PORT=5000
      - FRONTEND_URL=http://frontend.shvl.ia
      - BACKEND_URL=http://backend.shvl.ia
      - BACKEND_PORT=5001
      - FRONTEND_PORT=3000
    networks:
      - shvl-net
  mongo:
    hostname: mongo.shvl.ia
    container_name: mongo.shvl.ia
    image: 'mongo'
    ports:
      - "27017:27017"
    environment:
      - VIRTUAL_HOST=mongo.shvl.ia
    volumes:
      - mongo_data:/data/db
    networks:
      - shvl-net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo.shvl.ia/
    networks:
      - shvl-net
  cron-jobs:
    hostname: cron-jobs.shvl.ia
    container_name: cron-jobs.shvl.ia
    build:
      context: ./cron_jobs
      dockerfile: ./Dockerfile
    networks:
      - shvl-net
    depends_on:
      - backend
      - nginx-balancer
networks:
  shvl-net:
    external: true


