version: "3"
volumes:
  mongo_data:
    external: true
  portainer_data:
    external: true

services:
  backend:
    restart: always
    hostname: backend
    links:
      - mongo
    working_dir: /home/node/app
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    depends_on:
      - mongo
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://shvldb:shvldb2022@mongo:27017/backend-prod
      - DEFAULT_EMAIL_HOST_BACKEND=http://mail
      - CHOKIDAR_USEPOLLING=true
      - DEFAULT_EMAIL_HOST_PORT_BACKEND=1025
      - NODE_ENV=production
      - SENDGRID_KEY=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
      - MASTER_KEY=Sc4pGDcr8NeKPNouEXOQp1v784Dutmlt
      - JWT_SECRET=8EZ0QdhBOntJSuyZHXJHfVB4NCJQ4KqM
      - DEFAULT_EMAIL_BACKEND=adanyanezgonzalez@gmail.com
      - API_ROOT=/
      - WEB3_PROVIDERS_HTTP_PROVIDER=https://mainnet.infura.io/v3/3474ad1afab24ab49d8874963e26eeb7
    volumes:
      - ./backend:/home/node/app
    ports:
      - "5001"
    command: "npm run start"
    networks:
      - shvl-net
  frontend:
    restart: always
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000"
    networks:
      - shvl-net
    depends_on:
      - backend
  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer-ce
    environment:
      - VIRTUAL_HOST=portainer-caym-server.com
    networks:
      - shvl-net
  nginx-balancer:
    restart: always
    image: nginx:latest
    hostname: nginx-balancer
    container_name: nginx-balancer
    volumes:
      - ./nginx-balancer/nginx-backend-balancer:/etc/nginx/conf.d/
      - ./nginx-balancer/certbot/www:/var/www/certbot/:ro
      - ./nginx-balancer/certbot/conf:/etc/nginx/ssl/:ro
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shvl-net
    environment:
      - BACKEND_PORT=5001
      - FRONTEND_PORT=3000
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx-balancer/certbot/www/:/var/www/certbot/:rw
      - ./nginx-balancer/certbot/conf/:/etc/letsencrypt/:rw
  mongo:
    restart: always
    hostname: mongo
    container_name: mongo
    image: 'mongo'
    ports:
      - "27017:27017"
    environment:
      - VIRTUAL_HOST=mongo
      - MONGO_INITDB_ROOT_USERNAME=shvl
      - MONGO_INITDB_ROOT_PASSWORD=shvl2022
    volumes:
      - mongo_data:/data/db
    networks:
      - shvl-net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: shvl
      ME_CONFIG_MONGODB_ADMINPASSWORD: shvl2022
      ME_CONFIG_MONGODB_URL: mongodb://shvl:shvl2022@mongo:27017
    networks:
      - shvl-net
  cron-jobs:
    restart: always
    hostname: cron-jobs
    container_name: cron-jobs
    working_dir: /app
    volumes:
      - ./cron_jobs:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SELF_HOST=http://cron-jobs-server
      - SELF_PORT=4000
      - BACKEND_HOST=http://backend
      - BACKEND_PORT=5001
      - MASTER_KEY=Sc4pGDcr8NeKPNouEXOQp1v784Dutmlt
      - WEB3_PROJECT_ID=836e6a8258c14cae987e4dbc2dc4fe3b
      - WEB3_PROJECT_SECRET=8b9d757732c64cbba50f5def3e3529bf
      - OPENSEA_API_KEY=2f6f419a083c46de9d83ce3dbe7db601
    build:
      context: ./cron_jobs
      dockerfile: ./Dockerfile
    networks:
      - shvl-net
    depends_on:
      - backend
      - cron-jobs-server
  cron-jobs-server:
    restart: always
    hostname: cron-jobs-server
    container_name: cron-jobs-server
    working_dir: /app
    volumes:
      - ./cron_jobs-server:/app
    build:
      context: ./cron_jobs-server
      dockerfile: ./Dockerfile
    networks:
      - shvl-net
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NETWORK_OPENSEA_PORT=main
      - WEB3_PROVIDER=1
    command: "node /app/index.js"
networks:
  shvl-net:
    external: true


