apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: development
      name: development
    spec:
      ports:
        - name: "5000"
          port: 5000
          targetPort: 5000
      selector:
        io.kompose.service: development
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
      name: mongo
    spec:
      ports:
        - name: "27017"
          port: 27017
          targetPort: 27017
      selector:
        io.kompose.service: mongo
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-proxy
      name: nginx-proxy
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
        - name: "443"
          port: 443
          targetPort: 443
      selector:
        io.kompose.service: nginx-proxy
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: portainer
      name: portainer
    spec:
      ports:
        - name: "9000"
          port: 9000
          targetPort: 9000
      selector:
        io.kompose.service: portainer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: production
      name: production
    spec:
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000
      selector:
        io.kompose.service: production
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: test
      name: test
    spec:
      ports:
        - name: "4000"
          port: 4000
          targetPort: 4000
      selector:
        io.kompose.service: test
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: development
      name: development
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: development
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: development
        spec:
          containers:
            - args:
                - npm
                - run
                - dev
              env:
                - name: MONGO_URI
                  value: mongodb://mongo/backend-dev
                - name: NODE_ENV
                  value: development
                - name: PORT
                  value: "5000"
                - name: VIRTUAL_HOST
                  value: development.caym-server.com
              image: node:14
              name: development
              ports:
                - containerPort: 5000
              resources: {}
              volumeMounts:
                - mountPath: /home/node/app
                  name: development-hostpath0
              workingDir: /home/node/app
          hostname: development.caym-server.com
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/caym/Development/arquitecture/backend
              name: development-hostpath0
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
      name: mongo
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: mongo
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: mongo
        spec:
          containers:
            - image: mongo
              name: mongo
              ports:
                - containerPort: 27017
              resources: {}
              volumeMounts:
                - mountPath: /data/db
                  name: mongo-data
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/caym/Development/arquitecture
              name: mongo-data
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-proxy
      name: nginx-proxy
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: nginx-proxy
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: nginx-proxy
        spec:
          containers:
            - image: jwilder/nginx-proxy
              name: reverse-proxy
              ports:
                - containerPort: 80
                - containerPort: 443
              resources: {}
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /tmp/docker.sock
                  name: nginx-proxy-hostpath0
                  readOnly: true
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /var/run/docker.sock
              name: nginx-proxy-hostpath0
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: portainer
      name: portainer
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: portainer
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: portainer
        spec:
          containers:
            - args:
                - -H
                - unix:///var/run/docker.sock
              env:
                - name: VIRTUAL_HOST
                  value: portainer.caym-server.com
              image: portainer/portainer
              name: portainer
              ports:
                - containerPort: 9000
              resources: {}
              volumeMounts:
                - mountPath: /var/run/docker.sock
                  name: portainer-hostpath0
                - mountPath: /data portainer/portainer-ce
                  name: portainer-data
          hostname: portainer.caym-server.com
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /var/run/docker.sock
              name: portainer-hostpath0
            - hostPath:
                path: /home/caym/Development/arquitecture
              name: portainer-data
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: production
      name: production
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: production
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: production
        spec:
          containers:
            - args:
                - npm
                - run
                - prod
              env:
                - name: MONGO_URI
                  value: mongodb://mongo/backend-prod
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: "3000"
                - name: VIRTUAL_HOST
                  value: production.caym-server.com
              image: node:14
              name: production
              ports:
                - containerPort: 3000
              resources: {}
              volumeMounts:
                - mountPath: /home/node/app
                  name: production-hostpath0
              workingDir: /home/node/app
          hostname: production.caym-server.com
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/caym/Development/arquitecture/backend
              name: production-hostpath0
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: test
      name: test
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: test
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o kubernetes.yml --volumes hostPath
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: test
        spec:
          containers:
            - args:
                - npm
                - run
                - test
              env:
                - name: MONGO_URI
                  value: mongodb://mongo/backend-test
                - name: NODE_ENV
                  value: test
                - name: PORT
                  value: "4000"
                - name: VIRTUAL_HOST
                  value: test.caym-server.com
              image: node:14
              name: test
              ports:
                - containerPort: 4000
              resources: {}
              volumeMounts:
                - mountPath: /home/node/app
                  name: test-hostpath0
              workingDir: /home/node/app
          hostname: test.caym-server.com
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/caym/Development/arquitecture/backend
              name: test-hostpath0
    status: {}
kind: List
metadata: {}

