FROM node:16.15.0
RUN apt-get update
WORKDIR /app

COPY .babelrc /app/.babelrc
COPY .eslintrc /app/.eslintrc
COPY .travis.yml /app/.travis.yml
COPY package.json /app/package.json
COPY smtp.json /app/smtp.json
COPY vpk.json /app/vpk.json

COPY src /app/src

RUN npm install -D --legacy-peer-deps
RUN npm install  --legacy-peer-deps

